development:
  adapter: postgresql
  encoding: utf8
  database: raidit_dev
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: raidit_test
  username: postgres
  password:
