defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: raid_it_development

test:
  <<: *defaults
  database: raid_it_test

production:
  uri: <%= ENV["MONGOHQ_URL"] %>
